[package]
name = "prb02_iron-gcd"
version = "0.1.0"
edition = "2021"
authors = ["Pone Ding <poneding@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iron = "0.6.0"
router = "0.6.0"
urlencoded = "0.6.0"
